name: Post Balances

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs at 00:00 UTC daily

jobs:
  post-balances:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: scripts

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: yarn

    - name: Install dependencies
      run: yarn

    - run: yarn post-balances
      env:
        DISCORD_GAS_WEBHOOK: "{{ secrets.DISCORD_GAS_WEBHOOK }}"

