name: DIP Deposit
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9.13' 
      - name: Setup keys for deploy to the right address
      - name: 'Run Test'
        run: |
          pip install -r requirements.txt
          python main.py --url="dev.dual.finance" --seed="$SEED" --password="$PASSWORD"
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
          SEED: ${{ secrets.SEED }}
        shell: bash

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: failure-screenshot
          path: screenshot.png
          retention-days: 1
