name: DIP Deposit
on:
  schedule:
  - cron: "0 12 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9.13' 
      - name: 'Run Test'
        run: |
          pip install -r requirements.txt
          python main.py --url="https://dev.dual.finance" --seed="$SEED" --password="$PASSWORD" --token="SOL"
          python main.py --url="https://beta.dual.finance" --seed="$SEED" --password="$PASSWORD" --token="BTC"
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
          SEED: ${{ secrets.SEED }}
        shell: bash

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: failure-screenshot
          path: screenshot.png
          retention-days: 1
