name: DIP Deposit
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9.13' 
      - run: |
          pip install -r requirements.txt
          python main.py
        shell: bash

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: screenshot.png
          retention-days: 1
