name: Lint
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

defaults:
  run:
    working-directory: ./

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"
      - name: Install app dependencies
        working-directory: app
        run: yarn
      - name: Run ESLint on app
        working-directory: app
        run: yarn run eslint
