name: DIP Webdriver
on:
  schedule:
  - cron: "0 12 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9.13' 
      - name: 'Run Test'
        uses: GabrielBB/xvfb-action@v1
        with:
          run: |
            pip install -r requirements.txt
            python main.py --url="https://dev.dual.finance" --seed="$SEED" --password="$PASSWORD" --token="SOL"
            python main.py --url="https://beta.dual.finance" --seed="$SEED" --password="$PASSWORD" --token="SOL"
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
          SEED: ${{ secrets.SEED }}

      - name: 'Upload Screenshot'
        uses: actions/upload-artifact@v3
        with:
          name: failure-screenshot
          path: screenshot.png
          retention-days: 1

      - name: 'Upload Webpage'
        uses: actions/upload-artifact@v3
        with:
          name: failure-webpage
          path: failure.html
          retention-days: 1
